const $=id=>document.getElementById(id),MIN='2026-09-21',MAX='2026-11-30';let data=[];
const add=(s,n)=>{const d=new Date(s+'T12:00:00');d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const pretty=d=>new Date(d+'T12:00:00').toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'});
const routeRows=()=>data.filter(s=>s.port===$('route').value.split('|')[0]&&s.direction===$('route').value.split('|')[1]).sort((a,b)=>(a.date+a.depart).localeCompare(b.date+b.depart));
const duration=s=>{let [h,m]=s.depart.split(':').map(Number),[a,b]=s.arrive.split(':').map(Number),n=(a*60+b-h*60-m+1440)%1440;return Math.floor(n/60)+'h '+(n%60)+'m'};
function card(s){return `<article class="crossing"><div class="journey"><strong>${s.depart}</strong><span>${s.direction==='in'?s.port:'Isle of Man'}</span></div><div class="duration">${duration(s)}<span>→</span></div><div class="journey"><strong>${s.arrive}${s.arrive<s.depart?'<small>+1 day</small>':''}</strong><span>${s.direction==='in'?'Isle of Man':s.port}</span></div><div class="ship">${s.vessel==='M'?'Manannan':'Ben My Chree'}<small>Scheduled · ${pretty(s.date)}</small></div></article>`}
function render(){const day=$('date').value,rows=routeRows(),port=$('route').value.split('|')[0],minimum=port==='Larne'?'2026-09-02':MIN,today=rows.filter(s=>s.date===day),next=rows.find(s=>s.date>day);$('date').min=minimum;$('dayTitle').textContent=pretty(day);$('sailingCount').textContent=`${today.length} scheduled sailing${today.length===1?'':'s'}`;$('results').innerHTML=today.map(card).join('')||'<div class="empty">No sailing listed for this route on this date.</div>';
if(port==='Dublin'||day<minimum||day>MAX){$('sailingCount').textContent='Timetable unavailable for this selection';$('results').innerHTML='<div class="empty">'+(port==='Dublin'?'Dublin dates are not included in the linked autumn timetable.':`This route’s imported timetable covers ${pretty(minimum)} to ${pretty(MAX)}.`)+'</div>';$('insight').innerHTML='This is missing schedule coverage, not confirmation of no service. <a href="https://www.steam-packet.com/routes-and-times" target="_blank" rel="noopener">Check the operator’s timetable</a>.';$('week').replaceChildren();$('allRows').replaceChildren();$('allTitle').textContent='No imported timetable for this selection';return;}
 const alt=data.filter(s=>s.date===day&&s.direction===$('route').value.split('|')[1]&&s.port!==port&&['Heysham','Liverpool'].includes(port)&&['Heysham','Liverpool'].includes(s.port));
 $('insight').innerHTML=(today.length?'':'<strong>Why the gap?</strong> No departure appears in the supplied timetable for this route and date. ')+(next?`Next listed departure: <strong>${pretty(next.date)} at ${next.depart}</strong>. <button id="next">Show this sailing</button>`:'No later departure is included in this September–November timetable.')+(!today.length&&alt.length?`<p>${alt[0].port} has ${alt.length} departure${alt.length===1?'':'s'} that day. <button id="alternative">Show alternative port</button></p>`:'');
 if(port==='Larne'&&$('route').value.endsWith('|in')&&['2026-10-16','2026-11-16'].includes(day))$('insight').insertAdjacentHTML('afterbegin','<p><strong>Source date conflict:</strong> the November PDF section prints a Ben My Chree return dated 16 October. That row is withheld; a 16 November return is not assumed. Confirm with Steam Packet.</p>');
 if($('next'))$('next').onclick=()=>{$('date').value=next.date;render()};if($('alternative'))$('alternative').onclick=()=>{$('route').value=alt[0].port+'|'+alt[0].direction;render()};
 $('week').replaceChildren();for(let i=0;i<7;i++){const d=add(day,i),r=rows.filter(s=>s.date===d),b=document.createElement('button');b.className=i===0?'chosen':'';b.disabled=d>MAX;b.innerHTML=`<span>${pretty(d)}</span><strong>${d>MAX?'Outside data':r.length?r.map(s=>s.depart).join(' · '):'No sailing'}</strong>`;b.onclick=()=>{$('date').value=d;render()};$('week').append(b)}
 $('allTitle').textContent=`All ${rows.length} departures for this route`;$('allRows').innerHTML=rows.map(s=>`<tr><td>${pretty(s.date)}</td><td>${s.depart}</td><td>${s.arrive}${s.arrive<s.depart?' (+1 day)':''}</td><td>${s.vessel==='M'?'Manannan':'Ben My Chree'}</td></tr>`).join('');
 $('previous').disabled=day<=minimum;$('following').disabled=day>=MAX;
}
function init(rows){data=rows;const now=new Date().toLocaleDateString('en-CA');if(/^\d{4}-\d{2}-\d{2}$/.test(now)&&now>=MIN&&now<=MAX)$('date').value=now;render()}
 $('route').onchange=render;$('date').onchange=()=>{if($('date').value>=MIN&&$('date').value<=MAX)render()};$('previous').onclick=()=>{$('date').value=add($('date').value,-1);render()};$('following').onclick=()=>{$('date').value=add($('date').value,1);render()};$('print').onclick=()=>window.print();
fetch('sailings.json').then(r=>{if(!r.ok)throw Error('Unavailable');return r.json()}).then(init).catch(()=>{$('results').textContent='Timetable could not load. Please refresh or consult the operator.'});
